### ISSUE TITLE
Missing password for the p12 file

### ISSUE THREAD

**Issue by ujanssen** [datasharingframework/dsf-process-tutorial#3]
in exercises/exercise-0.md there is step 

5. Add the client certificate from test-data-generator/cert/Webbrowser_Test_User/Webbrowser_Test_User_certificate.p12 to your browser's certificate store

When I import the p12 file to firefox I'll be asked for a password. 

Where can I lookup the password for the p12 file?

**Comment by jaboehri** [comment]
Client certificate passwords should always be "password" in the tutorial. This information is missing in excercise-0.md. I will correct it and close the issue

**Comment by ujanssen** [comment]
the password is password
